export const API_ROUTES = {
    PROJECTS: '/api/project/me',
    LOGOUT: '/api/auth/logout',
    USER: '/api/user',
    USER_DELETE: '/api/user/delete',
    USER_PROMO_REDEEM: '/api/user/promo/redeem',
    SUBSCRIPTION: '/api/payment/subscription',
    SUBSCRIPTION_CHANGE: '/api/payment/subscription/change',
    SUBSCRIBE: '/api/payment/subscribe',
    RESULTS: (slug) => slug ? `/api/project/${slug}/results` : '/api/results',
    AUTH: (slug) => `/api/auth/${slug}/redirect`,
    PROJECT: (slug) => slug ? `/api/project/${slug}` : '/api/project',
    NEST: (slug) => `/api/project/${slug}/nest`,
    ADDFILES: (slug) => `/api/project/${slug}/addfiles`,
    LOGIN: (slug) => `/api/auth/${slug}/login`,
    STRIP_PROJECTS: '/api/strip/me',
    STRIP_PROJECT: (slug) => slug ? `/api/strip/${slug}` : '/api/strip',
    STRIP_ADDFILES: (slug) => `/api/strip/${slug}/addfiles`,
    STRIP_NEST: (slug) => `/api/strip/${slug}/nest`,
    STRIP_RESULTS: (slug) => `/api/strip/${slug}/results`,
};